fear: create mock, change createSitePointTemplate
htmlacademy-ecmascript/804273-big-trip-14 pull request #4
Opened 2021-04-06 10:59 UTC by tonyaber

2021-04-06 15:45 UTC, ademaro commented on src/view/trip-info.js
> +let minMax = require('dayjs/plugin/minMax');
ругается, тк подключаем через require, у нас es6 импорты, посмотри чем отличается)

2021-04-06 15:46 UTC, ademaro commented on src/const.js
> +const types = ['Taxi', 'Bus', 'Train', 'Ship', 'Transport', 'Drive', 'Flight', 'Check-in', 'Sightseeing', 'Restaurant'];
это константы для моков, либо в mocks/const.js или сразу в файл с генерацией моков)

Ну и их КАПСОМ пишем

2021-04-06 16:13 UTC, tonyaber commented on src/view/trip-info.js
> +let minMax = require('dayjs/plugin/minMax');
когда я делала просто 
import 'dayjs/plugin/minMax'; 
или
import 'dayjs/plugin/minMax.js'; 
- у меня не работало, в консоли высвечивалось сообщение, что нет таких функций, как min,max(
как вариант - можно переделать саму функцию генерации моков, чтобы каждая следующая дата уже была больше предедущей. Но мне показалось, что не стоит этим заморачиваться,  все равно с сервера должны прийти данные в нормальном порядке (или нет? )

2021-04-06 16:17 UTC, ademaro requested changes

2021-04-06 16:17 UTC, ademaro commented on src/mock/mock-point.js
> +//генерация случайных данных с массива для заполнения
И почему такое странное название? getRandomElementFromArray() какой-нибудь больше подошло бы...

2021-04-06 16:17 UTC, ademaro commented on src/mock/mock-point.js
> +    descriptions: generateDate(descriptions),
descriptions -> description

2021-04-06 16:17 UTC, ademaro commented on src/view/edit-point.js
> +  const TypeTemplate = types
почему с большой буквы?

2021-04-06 16:17 UTC, ademaro commented on src/view/edit-point.js
> +              <input id="event-type-${typeRadio.toLowerCase()}-1" class="event__type-input  visually-hidden" type="radio" name="event-type" value="${typeRadio.toLowerCase()}" ${check}>
для уникальных идентификаторов ещё и цифру менять бы нам

2021-04-06 16:17 UTC, ademaro commented on src/view/new-point.js
> +  const { date_from, date_to, type, offers, description } = point;
date_from -> dateFrom

2021-04-06 16:18 UTC, ademaro commented on src/view/trip-info.js
> +let minMax = require('dayjs/plugin/minMax');
Попробуй так: `import * as minMax from 'dayjs/plugin/minMax'`

2021-04-06 16:20 UTC, tonyaber commented on src/view/trip-info.js
> +let minMax = require('dayjs/plugin/minMax');
все, нашла как сделать. Решение было на гитхабе dayjs)

2021-04-06 16:25 UTC, ademaro requested changes
Давай сразу поправим и двинем дальше, пока открытым ПР оставляю

2021-04-06 16:25 UTC, ademaro commented on src/view/point.js
> +  }
Как минимум в отдельную ф-цию. И вообще, думаю, можно пересмотреть этот кусок кода...

2021-04-06 16:25 UTC, ademaro commented on src/view/point.js
> +                <button class="${isFavoriteTemplate}" type="button">
```js
<button class="event__favorite-btn ${is_favorite ? 'event__favorite-btn--active' : ''}" type="button">
```
Может, будем упрощать?)

2021-04-06 16:25 UTC, ademaro commented on src/view/price.js
> +  const basePrice = points.map((element) => element.base_price).reduce((accumulator, element) => accumulator + element);
переименовать переменные

2021-04-06 16:35 UTC, tonyaber commented on src/const.js
> +    id: 0,
все предложения - это импуты, у каждого свой фор и нейм. Через id я сделала привязку к ним. могу убрать и сверять по другому полю.

2021-04-07 12:00 UTC, ademaro commented on src/const.js
> +const cities = ['Amsterdam', 'Chamonix', 'Geneva', 'Paris', 'Berlin', 'Dresden'];
Так это тож константа) И ниже — так же, если что))

2021-04-07 12:01 UTC, ademaro commented on src/const.js
> +const TYPES = ['Taxi', 'Bus', 'Train', 'Ship', 'Transport', 'Drive', 'Flight', 'Check-in', 'Sightseeing', 'Restaurant'];
Эти константы — нужны для моков, давай в папку ./mocks/ сразу переместим

2021-04-07 12:06 UTC, ademaro commented on src/mock/mock-point.js
> +import { getRandomNumber, getRandomArray } from '../utils.js';
название файла — просто point хватит, он же в папке mock

2021-04-07 12:06 UTC, ademaro commented on src/mock/mock-point.js
> +const descriptions = [
тож константа для моков, давай порядок наведём сразу)

2021-04-07 12:08 UTC, ademaro requested changes
https://i.imgur.com/7XPj7hl.png — маленькие и большие буквы — имеют значение, нам надо с маленькой, давай тож сразу поправим.

2021-04-07 12:08 UTC, ademaro commented on src/mock/mock-point.js
> +//генерация данных для описания (город, его описание, набор фотографий и подписей к ним)
Давай всё-таки попробуем jsDoc нотацию для описания ф-ций

2021-04-07 12:08 UTC, ademaro commented on src/mock/mock-point.js
> +    base_price: getRandomNumber(100, 1000),
ключи до сих по snake_case, у нас — camelCase

2021-04-07 12:08 UTC, ademaro commented
Жду ещё небольших правок — и двинем дальше, думаю) Не хочется тащить просто в следующие задания такой код... Если хочешь — можем созвониться.

2021-04-07 17:44 UTC, ademaro approved these changes
Отлично! Летим дальше 🚀

2021-04-07 17:44 UTC, merged